global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rardi-web'
    static_configs:
      - targets: ['rardi-web:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'security-service'
    static_configs:
      - targets: ['rardi-security-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'customer-service'
    static_configs:
      - targets: ['rardi-customer-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['rardi-inventory-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['rardi-payment-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s